// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package sqlite

import (
	"context"
)

const insertBundle = `-- name: InsertBundle :exec
INSERT INTO bundles (bundle) VALUES (?)
`

func (q *Queries) InsertBundle(ctx context.Context, bundle string) error {
	_, err := q.db.ExecContext(ctx, insertBundle, bundle)
	return err
}
